# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='disLike',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='like',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='postID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='disLike',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.BigIntegerField(default=0),
        ),
    ]
