# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170302_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='nargroups',
            name='Name',
            field=models.CharField(max_length=150, unique=True, verbose_name='نام'),
        ),
    ]
