# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170503_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nargroups',
            name='Name',
            field=models.CharField(max_length=150, unique=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='nargroups',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
    ]
