# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 14:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170503_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='DisplayUserName',
            field=models.CharField(max_length=15, verbose_name='نام کاربری نمایشی'),
        ),
        migrations.AlterField(
            model_name='members',
            name='Group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.NarGroups', verbose_name='گروه'),
        ),
        migrations.AlterField(
            model_name='members',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='members',
            name='password',
            field=models.CharField(max_length=32, verbose_name='کلمه عبور'),
        ),
        migrations.AlterField(
            model_name='members',
            name='userName',
            field=models.CharField(max_length=32, unique=True, verbose_name='نام کاربری'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Text',
            field=models.TextField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Title',
            field=models.CharField(max_length=250, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='blog.members', verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='تاریخ انتشار'),
        ),
    ]
